import React from "react";

const Loader = () => {
  return (
    <div className="screen_loader animate__animated fixed inset-0 z-[60] grid place-content-center bg-[#fafafa] dark:bg-[#0e1e37]">
      <div className="relative flex h-[80px] w-[80px] items-center justify-center">
        <div></div>
        {/* <img src="/images/logo.png" className=" absolute h-[60px] w-[60px]  " /> */}
        {/* <svg width="150" height="150" viewBox="0 0 50 50">
          <g>
            <g transform="rotate(0 25 25)">
              <rect
                x="22"
                y="5"
                width="6"
                height="6"
                fill="#60A5FA"
                opacity="0.8"
              >
                <animate
                  attributeName="opacity"
                  values="0.8;0.2;0.8"
                  dur="2s"
                  begin="0s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
              <line
                x1="25"
                y1="11"
                x2="25"
                y2="20"
                stroke="#60A5FA"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate
                  attributeName="opacity"
                  values="0.5;0.1;0.5"
                  dur="2s"
                  begin="0s"
                  repeatCount="indefinite"
                ></animate>
              </line>
            </g>
            <g transform="rotate(60 25 25)">
              <rect
                x="22"
                y="5"
                width="6"
                height="6"
                fill="#60A5FA"
                opacity="0.8"
              >
                <animate
                  attributeName="opacity"
                  values="0.8;0.2;0.8"
                  dur="2s"
                  begin="0.3s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
              <line
                x1="25"
                y1="11"
                x2="25"
                y2="20"
                stroke="#60A5FA"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate
                  attributeName="opacity"
                  values="0.5;0.1;0.5"
                  dur="2s"
                  begin="0.3s"
                  repeatCount="indefinite"
                ></animate>
              </line>
            </g>
            <g transform="rotate(120 25 25)">
              <rect
                x="22"
                y="5"
                width="6"
                height="6"
                fill="#60A5FA"
                opacity="0.8"
              >
                <animate
                  attributeName="opacity"
                  values="0.8;0.2;0.8"
                  dur="2s"
                  begin="0.6s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
              <line
                x1="25"
                y1="11"
                x2="25"
                y2="20"
                stroke="#60A5FA"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate
                  attributeName="opacity"
                  values="0.5;0.1;0.5"
                  dur="2s"
                  begin="0.6s"
                  repeatCount="indefinite"
                ></animate>
              </line>
            </g>
            <g transform="rotate(180 25 25)">
              <rect
                x="22"
                y="5"
                width="6"
                height="6"
                fill="#60A5FA"
                opacity="0.8"
              >
                <animate
                  attributeName="opacity"
                  values="0.8;0.2;0.8"
                  dur="2s"
                  begin="0.8999999999999999s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
              <line
                x1="25"
                y1="11"
                x2="25"
                y2="20"
                stroke="#60A5FA"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate
                  attributeName="opacity"
                  values="0.5;0.1;0.5"
                  dur="2s"
                  begin="0.8999999999999999s"
                  repeatCount="indefinite"
                ></animate>
              </line>
            </g>
            <g transform="rotate(240 25 25)">
              <rect
                x="22"
                y="5"
                width="6"
                height="6"
                fill="#60A5FA"
                opacity="0.8"
              >
                <animate
                  attributeName="opacity"
                  values="0.8;0.2;0.8"
                  dur="2s"
                  begin="1.2s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
              <line
                x1="25"
                y1="11"
                x2="25"
                y2="20"
                stroke="#60A5FA"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate
                  attributeName="opacity"
                  values="0.5;0.1;0.5"
                  dur="2s"
                  begin="1.2s"
                  repeatCount="indefinite"
                ></animate>
              </line>
            </g>
            <g transform="rotate(300 25 25)">
              <rect
                x="22"
                y="5"
                width="6"
                height="6"
                fill="#60A5FA"
                opacity="0.8"
              >
                <animate
                  attributeName="opacity"
                  values="0.8;0.2;0.8"
                  dur="2s"
                  begin="1.5s"
                  repeatCount="indefinite"
                ></animate>
              </rect>
              <line
                x1="25"
                y1="11"
                x2="25"
                y2="20"
                stroke="#60A5FA"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate
                  attributeName="opacity"
                  values="0.5;0.1;0.5"
                  dur="2s"
                  begin="1.5s"
                  repeatCount="indefinite"
                ></animate>
              </line>
            </g>
            <circle
              cx="25"
              cy="25"
              r="8"
              fill="none"
              stroke="#60A5FA"
              strokeWidth="2"
            >
              <animate
                attributeName="r"
                values="8;9;8"
                dur="2s"
                repeatCount="indefinite"
              ></animate>
            </circle>
          </g>
        </svg> */}
        <svg width="150" height="150" viewBox="0 0 44 44">
          <circle
            cx="22"
            cy="22"
            r="6"
            fill="none"
            stroke="#60A5FA"
            strokeWidth="2"
          >
            <animate
              attributeName="r"
              from="6"
              to="20"
              dur="1.5s"
              begin="0s"
              repeatCount="indefinite"
            ></animate>
            <animate
              attributeName="opacity"
              from="1"
              to="0"
              dur="1.5s"
              begin="0s"
              repeatCount="indefinite"
            ></animate>
          </circle>
          <circle
            cx="22"
            cy="22"
            r="6"
            fill="none"
            stroke="#60A5FA"
            strokeWidth="2"
          >
            <animate
              attributeName="r"
              from="6"
              to="20"
              dur="1.5s"
              begin="0.5s"
              repeatCount="indefinite"
            ></animate>
            <animate
              attributeName="opacity"
              from="1"
              to="0"
              dur="1.5s"
              begin="0.5s"
              repeatCount="indefinite"
            ></animate>
          </circle>
        </svg>
      </div>
    </div>
  );
};

export default Loader;
